### ISSUE TITLE
Text breaking on fresh install

### ISSUE THREAD

**Issue by abbyck** [hedayaty/NetSpeed#131]
Hi, Please see the below video.

https://user-images.githubusercontent.com/19362717/122922652-7ad5b580-d381-11eb-83da-504e79e90d5a.mp4

As you can see, visually the text seems to be breaking. 
Tried adjusting the different label size, the number of digits etc.

On Gnome 40(Arch). Also tried on a fresh install. 
Any suggestions on what could be the issue?

**Comment by zman0900** [comment]
Also seeing this on Arch.  Gnome 40.2 and AMD graphics.  Looks like some kind of graphical corruption, but seems specific to this extension.

**Comment by abbyck** [comment]
@zman0900 Yes, only specific to this extension. I'm on Gnome Shell 40.2 with Intel Graphics. Able to reproduce on Wayland as well as on xorg.

**Comment by criess** [comment]
I can also confirm it on Fedora 34 (gnome-shell 40.2). behavior as on posted video.

**Comment by rinigus** [comment]
It is not specific for this extension. Same happens with https://extensions.gnome.org/extension/1085/simple-net-speed/

**Comment by barsa-net** [comment]
In my case, removing/commenting Line 135 removes tearing, I'm not fluent enough in JS to go deeper into the issue atm.
https://github.com/hedayaty/NetSpeed/blob/1598dc3bf767b30e273e5206af4d0331b95cb2e7/net_speed_status_icon.js#L129-L140

**Comment by ktamp** [comment]
For me, on Arch, tearing disappears only by setting
CLUTTER_PAINT=disable-clipped-redraws:disable-culling in /etc/environment,
as suggested in [https://wiki.archlinux.org/title/GNOME/Troubleshooting#Tear-free_video_with_Intel_HD_Graphics](url)

**Comment by ssieb** [comment]
It's not really tearing, it's bad redraws.  I really doubt that it has something to do with the graphics chipset.  I'm seeing it on AMD, NVidia, and Intel graphics.  That setting might workaround the problem by changing how redraws are done, maybe slowing them down or combining them or sonething.  The linked issue from a previous comment has an interesting comment.  It mentions that a screenshot will show it correctly.  I can verify that and I suspect it's because it causes a screen refresh.  Similar to what I've found that moving the mouse over it fixes it for a moment as well.  Given the name of that environment setting, I would guess that the wrong area is getting redrawn (which is what it looks like) and that setting forces a larger redraw area.  Does using just the first part (`CLUTTER_PAINT=disable-clipped-redraws`) fix the problem for you?

**Comment by hex007** [comment]
Also happens on raspberry Pi with gnome btw

**Comment by ktamp** [comment]
Just CLUTTER_PAINT=disable-clipped-redraws does fix the problem.

**Comment by aunetx** [comment]
I fixed this issue in #134 with a little hack, does it work for you too?

**Comment by abbyck** [comment]
I can confirm, #134 works for me without disabling clipped redraws. 
Thank you @aunetx <3

**Comment by hedayaty** [comment]
Seems to be an issue with gnome 40 (though does not impact many other extensions).
I have been using gnome 41 for a while and no problem.
